server:
    port: 8081
spring:
  application:
    name: razorpay
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpayDB
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

vault:
  master-key: X/HA8vtpA1jt9F9cMO10h5LwSVhPLXQbAXmh6j8o4zQ=

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: razorpay-super-secret-key-change-in-production-min-32chars
  access-token-expiry-ms: 900000
  refresh-token-expiry-days: 7
  max-sessions-per-user: 2